spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/saveconfig
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
  hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
    show_sql: false
    hbm2ddl.auto: validate


entitymanager.packagesToScan: org.oa.getmac
server:
  port: 8080
